/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pagos;

import conexion.Conexion;
import controladores.PagoJpaController;
import controladores.exceptions.NonexistentEntityException;
import entidades.Pago;
import entidades.Proveedor;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import pferreteria.CPago;

/**
 *
 * @author kevin
 */
public class historialDePagos extends javax.swing.JInternalFrame {

    Proveedor prov;
    modeloPagos mcp;
    controlPagos cp;
    
    /**
     * Creates new form historialDePagos
     */
    public historialDePagos(Proveedor p) {
        initComponents();
        borrarPago.setEnabled(Boolean.FALSE);
        this.prov = p;
        encontrarPagos();
    }

    public void setCp(controlPagos cp) {
        this.cp = cp;
    }
    
    public void encontrarPagos() {
        queProveedor.setText(queProveedor.getText() + prov.getNombre());
        EntityManagerFactory emf = Conexion.getConexion().getEmf();
        Query q = emf.createEntityManager().createNamedQuery("Pago.findByIdProveedor");
        q.setParameter("idProveedor", prov.getIdProveedor());
        List<Pago> pagosEncontrados = q.getResultList();
        ArrayList<CPago> listaDeCPagos = new ArrayList<>();
        if (!pagosEncontrados.isEmpty()) {
            info1.setText("");
            for (Pago p : pagosEncontrados) {
                listaDeCPagos.add(new CPago(p.getIdPago(), p.getFecha(), p.getTotal()));
            }
        } else {
            info1.setText("No se ha efectuado ningún pago a este Proveedor.");
        }
        mcp = new modeloPagos(listaDeCPagos, 1);
        jTable4.setModel(mcp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        queProveedor = new javax.swing.JLabel();
        info1 = new javax.swing.JLabel();
        borrarPago = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Historial de Pagos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        queProveedor.setText("Pagos Efectuados a: ");

        info1.setText("jLabel6");

        borrarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/borrar.png"))); // NOI18N
        borrarPago.setText("Eliminar");
        borrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPagoActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPago", "Monto", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable4MouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(queProveedor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(info1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(borrarPago)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(queProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(info1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrarPago)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPagoActionPerformed
        // TODO add your handling code here:
        PagoJpaController eliminador = new PagoJpaController(Conexion.getConexion().getEmf());
        int opc = JOptionPane.showConfirmDialog(this, "¿Realmente desea Eliminar éste pago?",
            "Confirmación de Eliminación.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opc == JOptionPane.OK_OPTION) {
            try {
                eliminador.destroy(mcp.obtenerPagos().get(jTable4.getSelectedRow()).getId());
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(this, "Algo salió mal, por favor intentelo de nuevo.", "Error al eliminar.", opc);
            }
        }
        Conexion.getConexion().getEmf().getCache().evictAll();
        encontrarPagos();
        borrarPago.setEnabled(Boolean.FALSE);
    }//GEN-LAST:event_borrarPagoActionPerformed

    private void jTable4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseReleased
        // TODO add your handling code here:
        borrarPago.setEnabled(Boolean.TRUE);
    }//GEN-LAST:event_jTable4MouseReleased

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        cp.buscarProveedores(1);
        cp.cargarCompras();
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarPago;
    private javax.swing.JLabel info1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel queProveedor;
    // End of variables declaration//GEN-END:variables
}
