/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pagos;

import conexion.Conexion;
import controladores.PagoJpaController;
import controladores.exceptions.NonexistentEntityException;
import entidades.Pago;
import entidades.Proveedor;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import pferreteria.CPago;

/**
 *
 * @author kevin
 */
public class historialDePagos extends javax.swing.JPanel {

    Proveedor prov;
    modeloPagos mcp;
    
    /**
     * Creates new form historialDePagos
     */
    public historialDePagos(Proveedor p) {
        initComponents();
        borrarPago.setEnabled(Boolean.FALSE);
        this.prov = p;
        encontrarPagos();
    }
    
    public void encontrarPagos() {
        queProveedor.setText(queProveedor.getText() + prov.getNombre());
        EntityManagerFactory emf = Conexion.getConexion().getEmf();
        Query q = emf.createEntityManager().createNamedQuery("Pago.findByIdProveedor");
        q.setParameter("idProveedor", prov.getIdProveedor());
        List<Pago> pagosEncontrados = q.getResultList();
        ArrayList<CPago> listaDeCPagos = new ArrayList<>();
        if (!pagosEncontrados.isEmpty()) {
            info1.setText("");
            for (Pago p : pagosEncontrados) {
                listaDeCPagos.add(new CPago(p.getIdPago(), p.getFecha(), p.getTotal()));
            }
        } else {
            info1.setText("No se ha efectuado ningún pago a este Proveedor.");
        }
        mcp = new modeloPagos(listaDeCPagos, 1);
        jTable4.setModel(mcp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queProveedor = new javax.swing.JLabel();
        info1 = new javax.swing.JLabel();
        borrarPago = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        queProveedor.setText("Pagos Efectuados a: ");

        info1.setText("jLabel6");

        borrarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/borrar.png"))); // NOI18N
        borrarPago.setText("Eliminar");
        borrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPagoActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPago", "Monto", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable4MouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(queProveedor)
                        .addContainerGap(288, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(borrarPago))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(info1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(queProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrarPago)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void borrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPagoActionPerformed
        // TODO add your handling code here:
        PagoJpaController eliminador = new PagoJpaController(Conexion.getConexion().getEmf());
        int opc = JOptionPane.showConfirmDialog(this, "¿Realmente desea Eliminar éste pago?",
            "Confirmación de Eliminación.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opc == JOptionPane.OK_OPTION) {
            try {
                eliminador.destroy(mcp.obtenerPagos().get(jTable4.getSelectedRow()).getId());
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(this, "Algo salió mal, por favor intentelo de nuevo.", "Error al eliminar.", opc);
            }
        }
        Conexion.getConexion().getEmf().getCache().evictAll();
        encontrarPagos();
        borrarPago.setEnabled(Boolean.FALSE);
    }//GEN-LAST:event_borrarPagoActionPerformed

    private void jTable4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseReleased
        // TODO add your handling code here:
        borrarPago.setEnabled(Boolean.TRUE);
    }//GEN-LAST:event_jTable4MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarPago;
    private javax.swing.JLabel info1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel queProveedor;
    // End of variables declaration//GEN-END:variables
}
