/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuarios;

import conexion.Conexion;
import controladores.UsuarioJpaController;
import entidades.Usuario;
import java.util.ArrayList;
import javax.persistence.Query;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Pablo Lopez <panlopezv@gmail.com>
 */
public class VistaUsuarios extends javax.swing.JInternalFrame {

    ModeloUsuarios modelo;
    UsuarioJpaController controladorU;
    
    /**
     * Creates new form VistaUsuarios
     */
    public VistaUsuarios() {
        initComponents();
        setVisible(Boolean.TRUE);
        controladorU = new UsuarioJpaController(vistas.Inicio.conexion.getEmf());
        cargarUsuarios();
        
    }
    
    public void cargarUsuarios(){
        setVisible(Boolean.TRUE);
        Query q = Conexion.getConexion().getEmf().createEntityManager().createNamedQuery("Usuario.findAll");
        try {
            modelo = new ModeloUsuarios(new ArrayList<>(q.getResultList()));
        } catch (Exception ex) {
            modelo = new ModeloUsuarios(new ArrayList<>());
        }
        tablaUsuarios.setModel(modelo);
    }
    
    public void crearUsuario(){
        JTextField usuario = new JTextField();
        JTextField nombre = new JTextField();
        JCheckBox esAdministrador = new JCheckBox("¿Es administrador?");
        JTextField contrasenya = new JPasswordField();
        JTextField verificacion = new JPasswordField();
        Object[] message = {
            "Usuario:", usuario,
            "Nombre:", nombre,
            "Contraseña:", contrasenya,
            "Verificar contraseña:", verificacion,
            esAdministrador,
        };
        int opcion = JOptionPane.showConfirmDialog(this, message, "Crear usuario.", JOptionPane.OK_CANCEL_OPTION);
        if (opcion == JOptionPane.OK_OPTION) {
            String registro = "";
            if(usuario.getText()==null || usuario.getText().compareTo("")==0){
                registro+="El campo usuario es obligatorio.\n\r";
            }
            if(nombre.getText()==null || nombre.getText().compareTo("")==0){
                registro+="El campo nombre es obligatorio.\n\r";
            }
            if(contrasenya.getText()==null || contrasenya.getText().compareTo("")==0){
                registro+="El campo contraseña es obligatorio.\n\r";
            }
            if(verificacion.getText()==null || verificacion.getText().compareTo("")==0){
                registro+="El campo verificación es obligatorio.\n\r";
            }
            if(contrasenya.getText().compareTo(verificacion.getText())!=0){
                registro+="La contraseña debe coincidir con la verificación.\n\r";
            }
            if(registro.compareTo("")!=0){
                JOptionPane.showMessageDialog(this, registro, "Error", JOptionPane.ERROR_MESSAGE);
                crearUsuario();
            }
            else{
                Query q = Conexion.getConexion().getEmf().createEntityManager().createNamedQuery("Usuario.findByUsuario");
                q.setParameter("usuario", usuario.getText());
                if(q.getResultList().isEmpty()){
                    Usuario nuevo = new Usuario(usuario.getText(), contrasenya.getText(), esAdministrador.isSelected(), nombre.getText());
                    controladorU.create(nuevo);
                    JOptionPane.showMessageDialog(this, "Usuario creado exitosamente.", "", JOptionPane.INFORMATION_MESSAGE);
                    cargarUsuarios();
                }
                else{
                    JOptionPane.showMessageDialog(this, "El usuario ingresado ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                    crearUsuario();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Usuarios");

        jScrollPane1.setViewportView(tablaUsuarios);

        jLabel1.setText("Usuarios:");

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCrear)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificar)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        crearUsuario();
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
        int fila=tablaUsuarios.getSelectedRow();
        if(fila>=0){
        }
        else{
            JOptionPane.showMessageDialog(null,"Debe seleccionar un usuario.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
